<a href="https://colab.research.google.com/github/Wiozie/ml-bootcamp/blob/main/supervised/01_basics/01_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import bibliotek

In [1]:
import numpy as np
import pandas as pd
import sklearn
sklearn.__version__

'1.2.2'

Generowanie danych

In [2]:
data = {
    'size': ['XL', 'L', 'M', 'L', 'M'],
    'color': ['red', 'green', 'blue', 'grren', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'female'],
    'price': [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']
}

df_raw = pd.DataFrame(data=data)
df_raw

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  grren  female  129.0     380     no
4    M    red  female   79.0     410    yes

Utworzenie kopii danych

In [3]:
df = df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   5 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  5 non-null      int64  
 5   bought  5 non-null      object 
dtypes: float64(1), int64(1), object(4)
memory usage: 368.0+ bytes


Zmiana typu danych i wstępna eksploracja

In [4]:
for col in ['size', 'color', 'gender', 'bought']:
  df[col] = df[col].astype('category')

df['weight'] = df['weight'].astype('float')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64 
 4   weight  5 non-null      float64 
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 812.0 bytes


In [5]:
df.describe()

price      weight
count    5.000000    5.000000
mean   119.000000  408.000000
std     48.476799   75.299402
min     79.000000  300.000000
25%     89.000000  380.000000
50%     99.000000  410.000000
75%    129.000000  450.000000
max    199.000000  500.000000

In [6]:
df.describe(include=['category']).T

count unique     top freq
size       5      3       L    2
color      5      4     red    2
gender     5      2  female    3
bought     5      2     yes    3

Label Encoder

In [7]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(df['bought'])
le.transform(df['bought'])

array([1, 0, 1, 0, 1])

In [8]:
le.classes_

array(['no', 'yes'], dtype=object)

In [9]:
df['bought'] = le.fit_transform(df['bought'])
df

size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  grren  female  129.0   380.0       0
4    M    red  female   79.0   410.0       1

In [ ]:
le.inverse_transform(df['bought'])
df['bought'] = le.inverse_transform(df['bought'])

OneHotencoder

In [11]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)
encoder.fit(df[['size']])

OneHotEncoder(sparse_output=False)

In [12]:
encoder.transform(df[['size']])

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [13]:
encoder.categories_

[array(['L', 'M', 'XL'], dtype=object)]

In [15]:
encoder = OneHotEncoder(drop='first', sparse_output=False)
encoder.fit(df[['size']])
encoder.transform(df[['size']])

array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

Pandas get_dummies

In [17]:
pd.get_dummies(data=df, drop_first=True, dtype=int)

price  weight  bought  size_M  size_XL  color_green  color_grren  \
0  199.0   500.0       1       0        1            0            0   
1   89.0   450.0       0       0        0            1            0   
2   99.0   300.0       1       1        0            0            0   
3  129.0   380.0       0       0        0            0            1   
4   79.0   410.0       1       1        0            0            0   

   color_red  gender_male  
0          1            0  
1          0            1  
2          0            1  
3          0            0  
4          1            0

Standaryzacja

In [18]:
print(f"{df['price']}\n")
print(f"Średnia: {df['price'].mean()}")
print(f"Odchylenie strandardowe: {df['price'].std():.4f}")

0    199.0
1     89.0
2     99.0
3    129.0
4     79.0
Name: price, dtype: float64

Średnia: 119.0
Odchylenie strandardowe: 48.4768


In [19]:
(df['price'] - df['price'].mean()) / df['price'].std()

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [23]:
from sklearn.preprocessing import StandardScaler

scaler_price = StandardScaler()
scaler_price.fit(df[['price']])
df['price'] = scaler_price.transform(df[['price']])

In [24]:
scaler_weight = StandardScaler()
df['weight'] = scaler_weight.fit_transform(df[['weight']])


In [ ]:
scaler = StandardScaler()
df[['price', 'weight']] = scaler.fit_transform(df[['price', 'weight']])